In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# Generate two 10x10 matrices with random numbers
matrix1 = np.random.randint(1, 10, size=(10, 10))
matrix2 = np.random.randint(1, 10, size=(10, 10))

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)

Matrix 1:
 [[4 6 4 3 6 2 6 4 8 5]
 [3 3 4 5 3 4 1 1 9 4]
 [1 2 9 6 4 1 2 8 4 5]
 [5 9 5 3 8 2 3 1 5 1]
 [5 2 2 4 8 1 1 6 3 9]
 [7 3 5 8 6 8 7 7 7 1]
 [9 6 4 5 5 5 5 8 9 1]
 [3 7 9 7 2 8 4 9 9 1]
 [1 9 3 5 5 7 1 3 8 8]
 [5 7 9 2 7 7 7 9 8 9]]
Matrix 2:
 [[9 8 5 9 8 5 4 4 4 5]
 [3 1 6 1 5 5 6 8 8 9]
 [1 5 5 4 1 3 7 9 6 8]
 [4 8 7 5 4 9 9 4 9 7]
 [5 7 3 3 2 2 9 6 3 9]
 [2 3 9 1 4 1 9 6 7 5]
 [7 7 6 6 8 5 2 3 1 1]
 [9 6 5 3 6 6 6 5 9 2]
 [2 6 7 7 6 5 7 7 1 1]
 [5 1 4 8 3 1 5 5 9 7]]


In [3]:
# Convert NumPy arrays to TensorFlow tensors
tensor1 = tf.convert_to_tensor(matrix1, dtype=tf.int32)
tensor2 = tf.convert_to_tensor(matrix2, dtype=tf.int32)

print("Tensor 1:\n", tensor1)
print("Tensor 2:\n", tensor2)

Tensor 1:
 tf.Tensor(
[[4 6 4 3 6 2 6 4 8 5]
 [3 3 4 5 3 4 1 1 9 4]
 [1 2 9 6 4 1 2 8 4 5]
 [5 9 5 3 8 2 3 1 5 1]
 [5 2 2 4 8 1 1 6 3 9]
 [7 3 5 8 6 8 7 7 7 1]
 [9 6 4 5 5 5 5 8 9 1]
 [3 7 9 7 2 8 4 9 9 1]
 [1 9 3 5 5 7 1 3 8 8]
 [5 7 9 2 7 7 7 9 8 9]], shape=(10, 10), dtype=int32)
Tensor 2:
 tf.Tensor(
[[9 8 5 9 8 5 4 4 4 5]
 [3 1 6 1 5 5 6 8 8 9]
 [1 5 5 4 1 3 7 9 6 8]
 [4 8 7 5 4 9 9 4 9 7]
 [5 7 3 3 2 2 9 6 3 9]
 [2 3 9 1 4 1 9 6 7 5]
 [7 7 6 6 8 5 2 3 1 1]
 [9 6 5 3 6 6 6 5 9 2]
 [2 6 7 7 6 5 7 7 1 1]
 [5 1 4 8 3 1 5 5 9 7]], shape=(10, 10), dtype=int32)


In [5]:
# Perform matrix addition
addition_result = tf.add(tensor1, tensor2)

print("Addition Result:\n", addition_result)

Addition Result:
 tf.Tensor(
[[13 14  9 12 14  7 10  8 12 10]
 [ 6  4 10  6  8  9  7  9 17 13]
 [ 2  7 14 10  5  4  9 17 10 13]
 [ 9 17 12  8 12 11 12  5 14  8]
 [10  9  5  7 10  3 10 12  6 18]
 [ 9  6 14  9 10  9 16 13 14  6]
 [16 13 10 11 13 10  7 11 10  2]
 [12 13 14 10  8 14 10 14 18  3]
 [ 3 15 10 12 11 12  8 10  9  9]
 [10  8 13 10 10  8 12 14 17 16]], shape=(10, 10), dtype=int32)


In [6]:
# Perform matrix multiplication (element-wise)
multiplication_result = tf.multiply(tensor1, tensor2)

print("Multiplication Result:\n", multiplication_result)

Multiplication Result:
 tf.Tensor(
[[36 48 20 27 48 10 24 16 32 25]
 [ 9  3 24  5 15 20  6  8 72 36]
 [ 1 10 45 24  4  3 14 72 24 40]
 [20 72 35 15 32 18 27  4 45  7]
 [25 14  6 12 16  2  9 36  9 81]
 [14  9 45  8 24  8 63 42 49  5]
 [63 42 24 30 40 25 10 24  9  1]
 [27 42 45 21 12 48 24 45 81  2]
 [ 2 54 21 35 30 35  7 21  8  8]
 [25  7 36 16 21  7 35 45 72 63]], shape=(10, 10), dtype=int32)


In [7]:
# Compute the transpose of the first matrix
transpose_result = tf.transpose(tensor1)

print("Transpose of Matrix 1:\n", transpose_result)

Transpose of Matrix 1:
 tf.Tensor(
[[4 3 1 5 5 7 9 3 1 5]
 [6 3 2 9 2 3 6 7 9 7]
 [4 4 9 5 2 5 4 9 3 9]
 [3 5 6 3 4 8 5 7 5 2]
 [6 3 4 8 8 6 5 2 5 7]
 [2 4 1 2 1 8 5 8 7 7]
 [6 1 2 3 1 7 5 4 1 7]
 [4 1 8 1 6 7 8 9 3 9]
 [8 9 4 5 3 7 9 9 8 8]
 [5 4 5 1 9 1 1 1 8 9]], shape=(10, 10), dtype=int32)


In [8]:
# Perform dot product (matrix multiplication)
dot_product_result = tf.linalg.matmul(tensor1, tensor2)

print("Dot Product Result:\n", dot_product_result)

Dot Product Result:
 tf.Tensor(
[[223 249 265 237 233 202 296 279 242 248]
 [137 191 223 188 165 157 257 225 197 196]
 [189 225 225 194 166 188 283 254 270 235]
 [178 218 229 179 189 177 278 263 213 266]
 [223 213 201 217 177 159 267 223 254 243]
 [286 348 354 272 295 270 389 323 314 287]
 [288 326 333 273 301 266 361 323 298 273]
 [243 307 365 241 275 272 400 362 350 295]
 [188 209 296 212 212 192 348 309 311 296]
 [323 338 389 323 319 264 438 416 395 368]], shape=(10, 10), dtype=int32)


In [9]:
# Generate a 10x10 matrix with random numbers
matrix = np.random.rand(10, 10)

# Ensure the matrix is invertible by making it positive definite
matrix = np.dot(matrix, matrix.T)
tensor = tf.convert_to_tensor(matrix, dtype=tf.float32)
# Perform matrix inversion
inverse_result = tf.linalg.inv(tensor)

print("Inverse Result:\n", inverse_result)

Inverse Result:
 tf.Tensor(
[[   6021.952   -22438.453    33424.12     36460.79    -14338.321
     3760.5505   16746.88    -32005.729   -14892.2705   -5372.948 ]
 [ -22438.56     83771.4    -124781.29   -136090.06     53520.918
   -14070.367   -62518.684   119488.35     55585.34     20051.121 ]
 [  33424.305  -124781.266   185875.92    202719.02    -79725.49
    20959.398    93124.83   -177989.11    -82799.984   -29869.201 ]
 [  36460.938  -136089.95    202718.9     221095.75    -86951.01
    22852.81    101565.08   -194117.95    -90305.84    -32577.22  ]
 [ -14338.362    53520.805   -79725.34    -86950.91     34197.332
    -8989.25    -39943.137    76343.07     35514.082    12811.826 ]
 [   3760.5632  -14070.358    20959.365    22852.79     -8989.256
     2371.5164   10500.1045  -20070.533    -9334.133    -3367.7073]
 [  16746.967   -62518.645    93124.78    101565.09    -39943.19
    10500.112    46659.11    -89174.66    -41484.395   -14964.554 ]
 [ -32005.885   119488.31   -177989.0

In [10]:
b = np.random.rand(10, 1)

# Convert vector b to TensorFlow tensor
b_tensor = tf.convert_to_tensor(b, dtype=tf.float32)

# Solve the system of linear equations
solution = tf.linalg.solve(tensor, b_tensor)

print("Solution to Ax = b:\n", solution)

Solution to Ax = b:
 tf.Tensor(
[[  5716.424 ]
 [-21315.998 ]
 [ 31751.521 ]
 [ 34634.13  ]
 [-13619.799 ]
 [  3575.4663]
 [ 15909.234 ]
 [-30403.639 ]
 [-14147.259 ]
 [ -5103.6885]], shape=(10, 1), dtype=float32)


In [11]:
# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = tf.linalg.eigh(tensor)

print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues:
 tf.Tensor(
[1.2222206e-06 4.4461872e-02 2.2959661e-01 2.5223997e-01 4.4245708e-01
 8.8896793e-01 1.5215180e+00 1.9193226e+00 2.9294190e+00 2.3345608e+01], shape=(10,), dtype=float32)
Eigenvectors:
 tf.Tensor(
[[ 0.08711582 -0.6659987   0.02746454  0.19007483 -0.3586632   0.09584018
  -0.09198642  0.4133463  -0.3471248   0.27264962]
 [-0.32520366 -0.12126729  0.585053    0.13079715  0.14796746  0.3605115
   0.52263135 -0.2305274  -0.03944309  0.20108978]
 [ 0.48442248  0.17308053  0.3554858   0.03122576  0.39146653  0.28831467
  -0.2948293   0.3775232   0.25542912  0.27743378]
 [ 0.5283253  -0.3089475   0.10670882 -0.06597169  0.07276046 -0.50525373
   0.16832389 -0.4740661   0.10334978  0.29215923]
 [-0.20777868  0.01667407 -0.23774731 -0.3167431   0.4299117  -0.3302019
   0.4104047   0.47972718 -0.10580145  0.3099661 ]
 [ 0.05461853  0.57850266  0.2605435  -0.17788577 -0.49848002 -0.15462716
  -0.00246613  0.02058654 -0.36313656  0.3976631 ]
 [ 0.24270177  0.03031003 -0.

In [12]:
# Perform Singular Value Decomposition (SVD)
s, u, v = tf.linalg.svd(tensor)

print("Singular Values:\n", s)
print("Left Singular Vectors (U):\n", u)
print("Right Singular Vectors (V):\n", v)

Singular Values:
 tf.Tensor(
[2.3345619e+01 2.9294200e+00 1.9193227e+00 1.5215186e+00 8.8896883e-01
 4.4245711e-01 2.5224039e-01 2.2959670e-01 4.4461779e-02 1.0466392e-06], shape=(10,), dtype=float32)
Left Singular Vectors (U):
 tf.Tensor(
[[ 0.27264974 -0.3471249  -0.41334754  0.09198223 -0.0958395  -0.3586669
   0.19007568  0.02747019 -0.6659965   0.08711651]
 [ 0.20108958 -0.03944275  0.23053302 -0.5226279  -0.36051092  0.14796618
   0.13078101  0.58505744 -0.12126858 -0.3252053 ]
 [ 0.27743393  0.25542924 -0.37752697  0.29482463 -0.28831404  0.39146796
   0.03121478  0.35548767  0.17307915  0.48442215]
 [ 0.29215917  0.10334962  0.4740669  -0.16832148  0.50525403  0.07275902
  -0.06597564  0.1067063  -0.30894735  0.52832586]
 [ 0.3099663  -0.10580124 -0.47972244 -0.41040912  0.33020017  0.42991194
  -0.31673726 -0.23775785  0.01667056 -0.20778126]
 [ 0.39766318 -0.3631368  -0.02058642  0.00246566  0.15462674 -0.49847668
  -0.17789695  0.2605378   0.5785053   0.05461808]
 [ 0.260162

In [13]:
# Define the function
def function(x):
    return x**3 + 2*x**2 + 3*x + 4

In [14]:
# Calculate the first derivative
x = tf.Variable(1.0)  # Define the variable

with tf.GradientTape() as tape:
    y = function(x)

first_derivative = tape.gradient(y, x)

print("First Derivative at x=1.0:", first_derivative.numpy())

First Derivative at x=1.0: 10.0


In [15]:
# Calculate the second derivative
with tf.GradientTape() as tape2:
    with tf.GradientTape() as tape1:
        y = function(x)
    first_derivative = tape1.gradient(y, x)
second_derivative = tape2.gradient(first_derivative, x)

print("Second Derivative at x=1.0:", second_derivative.numpy())

Second Derivative at x=1.0: 10.0


In [16]:
# Calculate the third derivative
with tf.GradientTape() as tape3:
    with tf.GradientTape() as tape2:
        with tf.GradientTape() as tape1:
            y = function(x)
        first_derivative = tape1.gradient(y, x)
    second_derivative = tape2.gradient(first_derivative, x)
third_derivative = tape3.gradient(second_derivative, x)

print("Third Derivative at x=1.0:", third_derivative.numpy())

Third Derivative at x=1.0: 6.0


In [17]:
# Define the sigmoid function
def sigmoid(x):
    return 1 / (1 + tf.exp(-x))

In [18]:
# Define the variable
x = tf.Variable(1.0)

# Calculate the gradient
with tf.GradientTape() as tape:
    y = sigmoid(x)

gradient = tape.gradient(y, x)

print("Gradient of the Sigmoid Function at x=1.0:", gradient.numpy())

Gradient of the Sigmoid Function at x=1.0: 0.19661194


In [19]:
# Calculate the second derivative
with tf.GradientTape() as tape2:
    with tf.GradientTape() as tape1:
        y = sigmoid(x)
    first_derivative = tape1.gradient(y, x)
second_derivative = tape2.gradient(first_derivative, x)

print("Second Derivative of the Sigmoid Function at x=1.0:", second_derivative.numpy())

Second Derivative of the Sigmoid Function at x=1.0: -0.09085775


In [20]:
# Calculate the third derivative
with tf.GradientTape() as tape3:
    with tf.GradientTape() as tape2:
        with tf.GradientTape() as tape1:
            y = sigmoid(x)
        first_derivative = tape1.gradient(y, x)
    second_derivative = tape2.gradient(first_derivative, x)
third_derivative = tape3.gradient(second_derivative, x)

print("Third Derivative of the Sigmoid Function at x=1.0:", third_derivative.numpy())

Third Derivative of the Sigmoid Function at x=1.0: -0.035325572
